Update patch set 3
Patch Set 3:

> Patch Set 2:
> 
> It looks a bit excessive. For example, the version in clang-4375569 (upcoming toolchain) does not export _Unwind_*. 
> Also these and more:
>     __extenddftf2;
>     __extendsftf2;
> 
> I suggest basing the export list off that or any newer version, it would be a lot smaller. That's when the toolchain switched to upstream cmake build, which correctly applies symbol visibility.

Ok, but they are required in the current version. See the build error below. We can remove them in the symbol file when we really upgrade to the 4375569 version. Rolled back to PS2 (and sorted the symbols)

out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_GetIP'
out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_DeleteException'
out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_SetGR'
out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_SetIP'
out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_Resume'
out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_GetRegionStart'
out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_GetLanguageSpecificData'
out/target/product/walleye/obj_asan/lib/libc++.vendor.so: error: undefined reference to '_Unwind_RaiseException'

Patch-set: 3